---
# Additional Facts
- name: Gather EC2 facts
  action: ec2_facts

- name: Add JRE ppa
  apt_repository: repo=ppa:webupd8team/java state=present

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: Get JRE
  shell: wget "http://ftp.osuosl.org/pub/funtoo/distfiles/oracle-java/jdk-7u80-linux-x64.tar.gz"

- name: Move JRE
  shell: sudo mv jdk-7u80-linux-x64.tar.gz /tmp/

- name: Local Path 
  shell: echo oracle-java7-installer oracle-java7-installer/local select /tmp | sudo /usr/bin/debconf-set-selections

- name: Approve
  shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: Install JRE
  apt: name=oracle-java7-installer update_cache=yes state=latest
    
- name: Install JNA
  apt: name=libjna-java update_cache=yes state=latest
 
- name: Install NTP daemon
  apt: pkg=ntp state=present

- name: Ensure NTP daemon autostart
  service: name=ntp enabled=yes

- name: Start NTP daemon
  service: name=ntp state=started
 
# Check whether cassandra is already installed
- name: Detect existing Cassandra installation at /opt/cassandra
  stat: path=/opt/cassandra
  register: state_of_cassandra_installation

# Cassandra download and installation
- name: Download Cassandra
  get_url: url=http://archive.apache.org/dist/cassandra/2.2.11/apache-cassandra-2.2.11-bin.tar.gz  dest=/tmp/cassandra.tar.gz
  when: state_of_cassandra_installation.stat.isdir is undefined

- name: Un  pack Cassandra
  unarchive: src=/tmp/cassandra.tar.gz dest=/opt copy=no
  when: state_of_cassandra_installation.stat.isdir is undefined

- name: Link Cassandra to /opt/cassandra
  file: "src=/opt/apache-cassandra-2.2.11 dest=/opt/cassandra state=link owner=ubuntu group=ubuntu"
  when: state_of_cassandra_installation.stat.isdir is undefined

# Folder setup
- name: Create Cassandra data and log directories
  file: "path={{ item }} state=directory owner=ubuntu group=ubuntu"
  with_items:
    - /var/log/cassandra
    - /mnt/cassandra/data
    - /mnt/cassandra/commitlog
    - /mnt/cassandra/saved_caches

# Dependency setup and configuration
- name: Link JNA
  file: "src=/usr/share/java/{{ item }} dest=/opt/cassandra/lib/{{ item }} state=link"
  with_items:
    - jna.jar
    - jna-platform.jar

- name: Copy Cassandra configuration files
  template: src={{ item }}.j2 dest=/opt/cassandra/conf/{{ item }}
  with_items:
    - cassandra-env.sh
    - cassandra.yaml
    - logback.xml



# Owner/Group Security
- name: Set user/group on Cassandra installation
  file: path=/opt/apache-cassandra-2.2.11 recurse=yes owner=ubuntu group=ubuntu
  
- name: Deploy Cassandra init.d script
  template: src=cassandra.j2 dest=/etc/init.d/cassandra mode=u=rwx,g=rx,o=rx
  
- name: Register Cassandra service for boot-time launch
  shell: update-rc.d cassandra defaults


- name: Copy authentication setup script
  template: src={{ item }}.j2 dest=/opt/cassandra/{{ item }} mode=600 owner=root group=root
  with_items:
    - check_connection.cql
    - setup_authentication.cql
    - disable_default_user.cql
  run_once: true

- name: reboot
  shell: sudo reboot
  ignore_errors: true

- pause: minutes=4 #wait for 4 minute to let the cluster come up
  run_once: true

#{{ ansible_default_ipv4.address }}
- name: Check if new authentication setup is already done
  shell: /opt/cassandra/bin/cqlsh  -f /opt/cassandra/check_connection.cql 
  register: state_of_authentication_setup
  ignore_errors: true
  run_once: true


- name: Remove authentication setup script
  file: path=/opt/cassandra/{{ item }} state=absent
  with_items:
    - check_connection.cql
    - setup_authentication.cql
    - disable_default_user.cql
  run_once: true
  #-u {{ jmx_username }} -pw {{ jmx_password }} repair -local 
